### ISSUE TITLE
关于事项的排序

### ISSUE THREAD

**Issue by Tokinouta** [Infinite-Lop/ExternalBrain#1]
有时候我可能会需要按照日期倒序，即最近的在最上面，最古老的在最下面。这样查看最近事项比较方便。
现在好像只有一种排列顺序，是按照日期正序。
不知道能不能添加选择排序的功能。
（虽然但是左边有快速滚动的按钮😂

**Comment by Infinite-Lop** [comment]
我我自己的使用习惯是，从来不在这个事件管理todo界面里面 留任何过去事项，所以没有过这个需求(*⊙~⊙)
![image](https://user-images.githubusercontent.com/44351792/156358433-80ae8e0e-4d9d-4244-b25b-87fb5ca73641.jpeg)
↑图中可见我从来都是清空了以前的事项的，，，事件管理这个库，对我来说就是记事本
如果要是我有需要记住的，我会记在别的库里头，但是排序功能的确是没有的
![image](https://user-images.githubusercontent.com/44351792/156358700-a7a6a178-63a5-4e35-ad0e-0550745749ff.jpeg)
<img width="618" alt="image" src="https://user-images.githubusercontent.com/44351792/156358892-b0c876d9-d554-4126-87bf-d7f21aa05441.png">
↑要记住的事情需要强行手动新建item容器
# 所以我推荐的办法是：
不用事件管理库做已完成事项的记录——因为会非常难以管理。把需要记住的过去事项储存在其它库，不重要的事项直接忘记（即删除）。
note：把需要记住的过去事项储存在其它库，可以直接复制过去，不必手动输入。编辑面板右侧有个🥎复制粘贴按钮，可以复制元素并粘贴到其它库的新位置。

# 让事件倒序的hack方法
打开命令行，输入以下代码：
app.fullitems.sort((a,b)=>{return a.截止日期>b.截止日期?-1:1})
即可按时间倒序。但此方法不会更改后端数据。
// 建议不要在倒序情况下对item进行编辑、保存，不然……你保存之后会有一大堆网络请求用于更改后端的储存顺序，前后端错误同步导致。（可能浪费流量，但不会对数据造成实质损害。视觉效果比较好，或许是个观赏项目……）

**Comment by Infinite-Lop** [comment]
我怀疑你没有意识到，可以新建库
<img width="99" alt="image" src="https://user-images.githubusercontent.com/44351792/156360437-0903952e-f9c1-4682-ba31-3fa0267f8133.png">

**Comment by Tokinouta** [comment]
我意识到了可以新建库，但我没意识到可以这么使😅

**Comment by Tokinouta** [comment]
感谢女王提供官方hack

**Comment by Infinite-Lop** [comment]
我感觉【倒序显示】是前端功能，不涉及后端修改，但现在我只能想到那个hack方法（且不太完善）
# 另一个官方hack
如果要在搜索结果中倒序显示，可以：
app.search_result.sort((a,b)=>{return a.item.截止日期>b.item.截止日期?-1:1})
↑这样的话，可以只显示搜索结果相关信息 的倒序
# 另一个tip
在搜索框输入   /.*/   可以匹配任意元素
![image](https://user-images.githubusercontent.com/44351792/156361806-6064a6be-1349-4806-98d0-abd9a9efb47e.jpeg)

**Comment by Infinite-Lop** [comment]
现在再close
